BEGIN TRANSACTION;
DELETE FROM SlangAlias WHERE phraseNormalized = 'джамбо';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslx5sdh9jpesnr54mody92pn', 'джамбо', 'джамбо', 'cmn3j5g0w004rvastwvjsiio9', 0.6, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslj3ovbonjd765w9spmbt4z8', 'джамбо', 'джамбо', 'cmn3j5fsy000pvastdq88i9gh', 0.6, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'флопарь';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl2r5prcc3q62cdse019hiru', 'флопарь', 'флопарь', 'cmn3j5fxr0033vast6w93j5u4', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'систендница';
DELETE FROM SlangAlias WHERE phraseNormalized = 'астера бокс';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl6ks6md0dwt1sgx3mfisf90', 'астера бокс', 'астера бокс', 'cmn3j5ftp0013vastglyb9y0j', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'мт про';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl0hp0rpgbgzlsmk5hq8hynu', 'мт про', 'мт про', 'cmn3j5ftv0016vasts041bj94', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = '150 дом';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl9yq0ytivu0j16mz65dx2jp', '150 дом', '150 дом', 'cmn3j5fu00019vastrw13y86t', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = '1200 нова';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslzcs9exr800mwmebkuexbys', '1200 нова', '1200 нова', 'cmn3j5fsd000evasti8mgcyq7', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'эплбоксы 20';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl2625mtyux6xe8p8qqkuti4', 'эплбоксы 20', 'эплбоксы 20', 'cmn3j5fzr0043vast4m63npq4', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'си клемп';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl7zlxfjmpdj2ulbx5p0ymmo', 'си клемп', 'си клемп', 'cmn3j5g1a004zvastu7iqhgzn', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'сиклемп';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslzvw84me981cefel9vf8qri', 'сиклемп', 'сиклемп', 'cmn3j5g1a004zvastu7iqhgzn', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = '240 панель квадрат';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl7rk3vteqe51cpm6emp729a', '240 панель квадрат', '240 панель квадрат', 'cmn3j5fsn000jvasttuqhk5b5', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = '12 силк';
DELETE FROM SlangAlias WHERE phraseNormalized = 'софт на нову 600';
DELETE FROM SlangAlias WHERE phraseNormalized = 'зарядка для вимаунтов двойная';
DELETE FROM SlangAlias WHERE phraseNormalized = 'веревки';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslgmy338leylkzbzascjw6wu', 'веревки', 'веревки', 'cmn3j5g010049vastks2ybu0i', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'с клемп';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslqterkgohu9mn30fbzojg7z', 'с клемп', 'с клемп', 'cmn3j5g1a004zvastu7iqhgzn', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'гена';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl04x060jlideggny7h6wiu5', 'гена', 'гена', 'cmn3j5g4w0070vastpe2j8hzr', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'мт';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslfmmf5yml2ap894i3p7dgp5', 'мт', 'мт', 'cmn3j5ftv0016vasts041bj94', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'уважуха';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslkv1xhlmjjrgzl0biiss8ej', 'уважуха', 'уважуха', 'cmn3j5fzb003vvaste6xw7gxy', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'новы 1200';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslzmiqn6wuokmu5dl4shag53', 'новы 1200', 'новы 1200', 'cmn3j5fsd000evasti8mgcyq7', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'мс кит';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslt2sda7bp7w62igqytk2fa7', 'мс кит', 'мс кит', 'cmn3j5ftz0018vastkp73cuvk', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'вайс';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslpe7op86e6roral7voiit5u', 'вайс', 'вайс', 'cmn3j5g1h0053vastnw58qmu0', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'стреп';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csld95cg5btlkvqqlnqm6md4v', 'стреп', 'стреп', 'cmn3j5g1t0059vastsnpdxnmp', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'эплбоксы 10';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslusiw1w2r6lpena4l884zot', 'эплбоксы 10', 'эплбоксы 10', 'cmn3j5fzv0045vast0g0d6ys1', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'эплбоксы 5';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl7kan9dbdczu539m7qujh2f', 'эплбоксы 5', 'эплбоксы 5', 'cmn3j5fzt0044vastd6xvaws8', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = '8 тибон';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslebi16zd58neya2s206e2vg', '8 тибон', '8 тибон', 'cmn3j5g05004bvast4mgfq9ie', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = '12 тибон';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl8hk5in8ii30d8sujoe9469', '12 тибон', '12 тибон', 'cmn3j5g06004cvastwarsrk6i', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'куплер 360';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csleticgs0id7dch8wk6p0tch', 'куплер 360', 'куплер 360', 'cmo17b23t008ixseww15ngd45', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'спотлайт 36';
DELETE FROM SlangAlias WHERE phraseNormalized = 'хейзер большой';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl1b8etb3g2vvoqeuxkqvaw2', 'хейзер большой', 'хейзер большой', 'cmn3j5fvo0024vast1jochq5z', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'ручной хейзер';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslia5rbfbagmxb3e0vajew5f', 'ручной хейзер', 'ручной хейзер', 'cmn3j5fvm0023vastf877maoc', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'колодка 63 380 3х32 380';
DELETE FROM SlangAlias WHERE phraseNormalized = 'b150';
DELETE FROM SlangAlias WHERE phraseNormalized = '2 виндпапа';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl0sg65uauyeuhrsddphw7z8', '2 виндпапа', '2 виндпапа', 'cmn3j5fw2002cvastv2i1jxfs', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = '6 кабла 6 тройников';
DELETE FROM SlangAlias WHERE phraseNormalized = 'астеро бокс';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslng4bboypd016mq7qh88bcr', 'астеро бокс', 'астеро бокс', 'cmn3j5ftp0013vastglyb9y0j', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'текстиля на фросты';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslklj4algus6dglwbp42wi9p', 'текстиля на фросты', 'текстиля на фросты', 'cmn3j5fyk003hvastttjxeawc', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'a100 на колесах';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl571diztt59zaf0k1g1hwjc', 'a100 на колесах', 'a100 на колесах', 'cmn3j5fvx0029vast7u6dxqtp', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'жидкое зеркало';
DELETE FROM SlangAlias WHERE phraseNormalized = 'ящик';
DELETE FROM SlangAlias WHERE phraseNormalized = 'хорьки маленькие';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csls5ghxezz1udt0fgrmuwxhq', 'хорьки маленькие', 'хорьки маленькие', 'cmn3j5g1c0050vast3ha5oh3a', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'прищепки маленькие';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslx0avebf65fe7qvetb5zrd7', 'прищепки маленькие', 'прищепки маленькие', 'cmn3j5g29005hvastkmmmeklx', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'синее кабло';
DELETE FROM SlangAlias WHERE phraseNormalized = 'пленка';
DELETE FROM SlangAlias WHERE phraseNormalized = 'куб';
DELETE FROM SlangAlias WHERE phraseNormalized = 'силк 12';
DELETE FROM SlangAlias WHERE phraseNormalized = 'флоппи 36';
DELETE FROM SlangAlias WHERE phraseNormalized = 'насадка бабл на мс про';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl1nmxrkmf7ru0ss1ibxzzx2', 'насадка бабл на мс про', 'насадка бабл на мс про', 'cmn3j5fuh001ivastd6hxoy2j', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'дом 150 на 52';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslmk23hp47x8d0g17sspx7l9', 'дом 150 на 52', 'дом 150 на 52', 'cmn3j5fu6001cvastw43yyxw8', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'труба 2 метра';
DELETE FROM SlangAlias WHERE phraseNormalized = 'стропа безхраповая';
DELETE FROM SlangAlias WHERE phraseNormalized = 'спот лайт 36';
DELETE FROM SlangAlias WHERE phraseNormalized = 'прищепка с гибкой';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslyw2lscvgomuzohpptmu7cw', 'прищепка с гибкой', 'прищепка с гибкой', 'cmn3j5g0y004svast5purvb6k', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'кабель бытовой';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csluls68stnhi3d5qpr58iwq9', 'кабель бытовой', 'кабель бытовой', 'cmn3j5g4b006ovastxiy8lfbb', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'уши трубной рамы 42';
DELETE FROM SlangAlias WHERE phraseNormalized = 'дом 150 на 2600';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslka6taabh6w9gzbx2pd4841', 'дом 150 на 2600', 'дом 150 на 2600', 'cmn3j5fu6001cvastw43yyxw8', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'джамбо грип хэд';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl65b7auckblh69wzqt0bmvl', 'джамбо грип хэд', 'джамбо грип хэд', 'cmn3j5g0w004rvastwvjsiio9', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'текстиль 12 силк';
DELETE FROM SlangAlias WHERE phraseNormalized = 'зарядка для вимаунтов';
DELETE FROM SlangAlias WHERE phraseNormalized = 'двойная зарядка для вимаунтов';
DELETE FROM SlangAlias WHERE phraseNormalized = 'кабло быт';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csljh17fo2uvlzm4b9mlak6m2', 'кабло быт', 'кабло быт', 'cmn3j5g4b006ovastxiy8lfbb', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'гринболы кит';
DELETE FROM SlangAlias WHERE phraseNormalized = '240с';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslsuc2ni79enr44tf7dhzw8p', '240с', '240с', 'cmn3j5fsn000jvasttuqhk5b5', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'лайтдом 90 150';
DELETE FROM SlangAlias WHERE phraseNormalized = 'павослимы все';
DELETE FROM SlangAlias WHERE phraseNormalized = 'текстиль';
DELETE FROM SlangAlias WHERE phraseNormalized = 'кит текстилей на фрост раму';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslk8fryki6uc70hi45yrgrcx', 'кит текстилей на фрост раму', 'кит текстилей на фрост раму', 'cmn3j5fyk003hvastttjxeawc', 0.9, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;