BEGIN TRANSACTION;
DELETE FROM SlangAlias WHERE phraseNormalized = 'желтая тележка';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csllqyrelyj0ed1s1tnqp7do9', 'желтая тележка', 'желтая тележка', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'желтая телега';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslx8ewagb0tadvp2s35nwhsg', 'желтая телега', 'желтая телега', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'тележка';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslv3n390jel38fdobsptbuq8', 'тележка', 'тележка', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'телега';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl8dag3bhi44z4nei799rtjf', 'телега', 'телега', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'маглайнер';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl79r7za1rs64qn1dl36hep9', 'маглайнер', 'маглайнер', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'маглайнеры';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslpienapjksua4djlypytghx', 'маглайнеры', 'маглайнеры', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'телега для мешков';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslsreip3ouhev5rtckvf7imz', 'телега для мешков', 'телега для мешков', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'тележка под си стенды';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('csl6il5he7g67s6vdujbov0jn', 'тележка под си стенды', 'тележка под си стенды', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'телега стенли';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslpzx8he8y5dgng88t1hepds', 'телега стенли', 'телега стенли', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'систендница';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslstn7ywtpgz18b9wu1a0jf0', 'систендница', 'систендница', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized = 'тележка под плоский';
INSERT OR IGNORE INTO SlangAlias (id, phraseNormalized, phraseOriginal, equipmentId, confidence, source, usageCount, lastUsedAt, createdAt, updatedAt) VALUES ('cslby2hgp1ma40b5ny4jlokux', 'тележка под плоский', 'тележка под плоский', 'cmn3j5g4f006qvastwiw2bf6k', 0.75, 'MANUAL_ADMIN', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
COMMIT;