BEGIN TRANSACTION;
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('ceq3yjgm339ncribbqcrbbi72','manual-ruchka-b200','COUNT',0,'Штативы / Стойки','Ручка для стойки B200',10,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('ceq7akuspa290m9lksvto9q3y','manual-sapogi','COUNT',0,'Грип','Сапоги',10,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('ceqeezvy4ctvq29svt1lrtu4d','manual-yaschik','COUNT',0,'Грип','Ящик',10,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('ceqxrj7uu4gfruzbl9qy2w1tl','manual-trass-holder','COUNT',0,'Грип','Трасс холдер (держатель фермы)',4,300,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('ceqsebw600s3jd6c4lnlke1gw','manual-otrazhatel-plenka','COUNT',0,'Флаги/каттеры/флоппи','Отражатель (пена/плёнка)',5,100,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('ceqv51u9dlvwbe893g3kk6a73','manual-block-typec-2','COUNT',0,'Электрика/Коммутация','Блок Type-C двойной',10,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('cequ01gluxbdb1dt0w3tknaon','manual-kolya','COUNT',0,'Грип','Колья (колышки)',10,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('ceq1fl37t6kvqthuka4ovv4k4','manual-sistendnitsa','COUNT',0,'Грип','Систендница (тележка для C-стендов)',5,500,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO Equipment (id,importKey,stockTrackingMode,sortOrder,category,name,totalQuantity,rentalRatePerShift,createdAt,updatedAt) VALUES ('ceqw0b57m0ddzh9u4yadvgqif','manual-light-dome-120','COUNT',0,'Насадки на приборы','Софтбокс Aputure Light Dome 120',4,1000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
UPDATE Equipment SET rentalRatePerShift=300, totalQuantity=10, name='Верёвка (СС 48-прядная, Альпекс/Канат)', updatedAt=CURRENT_TIMESTAMP WHERE id='cmn3j5g010049vastks2ybu0i';
DELETE FROM SlangAlias WHERE phraseNormalized='лайт маны';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslzti8nce8f7jd8xmgxrhdx8','лайт маны','лайт маны','cmn3j5fsu000nvasthet07l46',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='лайтманы';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslk2p0l35dxj02ewnd3nl9gk','лайтманы','лайтманы','cmn3j5fsu000nvasthet07l46',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='лайт ман';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csltlkje64fnlqktjuj8nhfxe','лайт ман','лайт ман','cmn3j5fsu000nvasthet07l46',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='лайтман 12';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl9npixe2w4gb8cecaxr59ui','лайтман 12','лайтман 12','cmn3j5fsu000nvasthet07l46',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='сетки';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslef5uyeq8f2tj0mk8qfygzy','сетки','сетки','cmn3j5fxx0036vastxsdlebux',0.7,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='пенки';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslp4izfwl6wsk905a51m217x','пенки','пенки','cmn3j5fya003cvast840k2mu2',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='стропа безхраповая';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csla9gj43jjmqu35u2ao214a1','стропа безхраповая','стропа безхраповая','cmn3j5g1t0059vastsnpdxnmp',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='стропа без храповика';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslhu84k4m118v80erj2b7k3i','стропа без храповика','стропа без храповика','cmn3j5g1t0059vastsnpdxnmp',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='строп безхраповый';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslgodt2pai6bl64wu7dep2rs','строп безхраповый','строп безхраповый','cmn3j5g1t0059vastsnpdxnmp',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='астеро магниты';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslw7e0c7yo4qtguyw5vgulxz','астеро магниты','астеро магниты','cmn3j5ftj0010vastmaow45ij',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='астера магниты';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslductxj4hvab3nbrq3q7b8t','астера магниты','астера магниты','cmn3j5ftj0010vastmaow45ij',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='магниты астера';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csly7fct78dx0w9oj5j2xj8z5','магниты астера','магниты астера','cmn3j5ftj0010vastmaow45ij',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='магниты на астеры';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslxac6jhdlvik8puha42y39y','магниты на астеры','магниты на астеры','cmn3j5ftj0010vastmaow45ij',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='астеро магнит';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl9jnkwo1s7wk2e1m80l48z2','астеро магнит','астеро магнит','cmn3j5ftj0010vastmaow45ij',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='грипхеды';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl0azvi5fawgbrrrjgxnwh8b','грипхеды','грипхеды','cmn3j5g0w004rvastwvjsiio9',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='грип хеды';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csln8j6uqosxdmxzg8sz9dxe0','грип хеды','грип хеды','cmn3j5g0w004rvastwvjsiio9',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='грипхед';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslpjbe3g3r1d6gvi26sfb3ef','грипхед','грипхед','cmn3j5g0w004rvastwvjsiio9',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='сенд бег';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl19dz6srd95td6ebx3opx5r','сенд бег','сенд бег','cmn3j5g000048vastu5p5xss0',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='сендбег';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl0cdwbjwgp8zu9wwghv49xa','сендбег','сендбег','cmn3j5g000048vastu5p5xss0',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='сендбеги';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslc1fy5n5cjuhq2lwoz9ebnk','сендбеги','сендбеги','cmn3j5g000048vastu5p5xss0',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='санд бег';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslazkf4jb3cudco0dcqp44k0','санд бег','санд бег','cmn3j5g000048vastu5p5xss0',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='чекенборд 8';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csltkwalxhq3bo6yc6cc7pg23','чекенборд 8','чекенборд 8','cmn3j5fzi003zvastra1mk6h0',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='чекерборд 8';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslk472qx9vfp8miho7ymryiu','чекерборд 8','чекерборд 8','cmn3j5fzi003zvastra1mk6h0',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='чекенборд 8 и 12';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl3h4eut2uwrl53fv3q2bj1i','чекенборд 8 и 12','чекенборд 8 и 12','cmn3j5fzi003zvastra1mk6h0',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='малые автополя';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslvyw3kjndgkm1h059cjqunt','малые автополя','малые автополя','cmn3j5fx1002tvastu1nv6rwd',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='автополя малые';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl3dwsztqjshy3jlhnwxzmwc','автополя малые','автополя малые','cmn3j5fx1002tvastu1nv6rwd',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='малое автополе';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslfbc0za7mnx6x236it38auy','малое автополе','малое автополе','cmn3j5fx1002tvastu1nv6rwd',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='маленькое автополе';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl8lg22nflszu6dtxxhobe1t','маленькое автополе','маленькое автополе','cmn3j5fx1002tvastu1nv6rwd',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='30 с стенд';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslxwa4bc8vfqdjbodiaxnaj8','30 с стенд','30 с стенд','cmn3j5fwa002gvastyyx6xxjl',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='30 стенд';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csluk5bosp8eyx35zkgscarcx','30 стенд','30 стенд','cmn3j5fwa002gvastyyx6xxjl',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='с стенд 30';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csljitmwim8hqvnsn2uwhy7fg','с стенд 30','с стенд 30','cmn3j5fwa002gvastyyx6xxjl',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='систенд 30';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslw2cr7jpf7pkiqr5srm7rvn','систенд 30','систенд 30','cmn3j5fwa002gvastyyx6xxjl',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='уши трубной рамы 42';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl21ptafana065dwduh5ty23','уши трубной рамы 42','уши трубной рамы 42','cmn3j5g0n004mvast5fkburol',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='углы 6 рамы';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl03bpifly3kxkyrlec20d59','углы 6 рамы','углы 6 рамы','cmn3j5g0n004mvast5fkburol',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='уши рамы 42';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csllnclcxibyujvpgvjmaiipk','уши рамы 42','уши рамы 42','cmn3j5g0n004mvast5fkburol',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='уши от 42 рамы';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslga1g4n2mw0ys6o941splbu','уши от 42 рамы','уши от 42 рамы','cmn3j5g0n004mvast5fkburol',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='углы рамы 42';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslv7oimytsngb8e0bl1w9lwi','углы рамы 42','углы рамы 42','cmn3j5g0n004mvast5fkburol',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='балб на мс про';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslpdufnma807l701sa04usrl','балб на мс про','балб на мс про','cmn3j5fuh001ivastd6hxoy2j',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='диффузор балб';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csllqq8hs397ukq8lyibev3fk','диффузор балб','диффузор балб','cmn3j5fuh001ivastd6hxoy2j',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='бабл дифузер';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslw303mbu8il0s4c7ximxyqr','бабл дифузер','бабл дифузер','cmn3j5fuh001ivastd6hxoy2j',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='балб мс про';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl7vw9xlk7lokv03qb8zalo2','балб мс про','балб мс про','cmn3j5fuh001ivastd6hxoy2j',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='балба мс про';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslck23lsk03oqsnzwv04e71c','балба мс про','балба мс про','cmn3j5fuh001ivastd6hxoy2j',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='бабл диффузер';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl34odgdmkw1m7tjfsxu5pmm','бабл диффузер','бабл диффузер','cmn3j5fuh001ivastd6hxoy2j',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='трубный тонкий';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslvxwdhbb2h5d4s1tmjwkqa8','трубный тонкий','трубный тонкий','cmn3j5g0d004gvastr3nefnlh',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='труба тонкая';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslricjnk1lxnx3zofjb5ynl2','труба тонкая','труба тонкая','cmn3j5g0d004gvastr3nefnlh',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='тонкая труба';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl5lichnwhxlmphadi2dqu8t','тонкая труба','тонкая труба','cmn3j5g0d004gvastr3nefnlh',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='труба 2 метра';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslozp79vafa3s92925pjbutq','труба 2 метра','труба 2 метра','cmn3j5g0b004fvastmxrnr7kn',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='труба 2 4 метра';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslalatywvzpfxqbsmtwo5xnb','труба 2 4 метра','труба 2 4 метра','cmn3j5g0b004fvastmxrnr7kn',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='2 4 метра труба';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csllnm6upyd2w8b8my6eesijs','2 4 метра труба','2 4 метра труба','cmn3j5g0b004fvastmxrnr7kn',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='труба 24 метра';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslqyfrym5g6r1xncxu0kmrr3','труба 24 метра','труба 24 метра','cmn3j5g0b004fvastmxrnr7kn',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='2 метра труба';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslqs5xxda0i6gvwfhrcajvyw','2 метра труба','2 метра труба','cmn3j5g0b004fvastmxrnr7kn',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='ручка на б200';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl5xpcw4bhm9a5zuuwov84r7','ручка на б200','ручка на б200','ceq3yjgm339ncribbqcrbbi72',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='ручка для б200';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslssj8vg7du3gg1vr3n900ek','ручка для б200','ручка для б200','ceq3yjgm339ncribbqcrbbi72',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='ручка б200';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslr3r0doh4pxu1sphk7yraet','ручка б200','ручка б200','ceq3yjgm339ncribbqcrbbi72',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='ручка б 200';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslzfb9hn2kkiljjia8s7z0ea','ручка б 200','ручка б 200','ceq3yjgm339ncribbqcrbbi72',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='сапоги';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csldt9ylcl9e1m5i2lbcctvx4','сапоги','сапоги','ceq7akuspa290m9lksvto9q3y',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='сапог';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csld40l293hjlgyki3e3g23vm','сапог','сапог','ceq7akuspa290m9lksvto9q3y',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='ящик';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslosr2fz4ck25bj5shzcp721','ящик','ящик','ceqeezvy4ctvq29svt1lrtu4d',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='ящики';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslxolr7jenq6gc3ugfc1z5sr','ящики','ящики','ceqeezvy4ctvq29svt1lrtu4d',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='трасс холдер';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl3fxub8rz5zmla9y2ju5bbs','трасс холдер','трасс холдер','ceqxrj7uu4gfruzbl9qy2w1tl',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='трас холдер';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csly1c4dqvkjij8yvhic0dz6r','трас холдер','трас холдер','ceqxrj7uu4gfruzbl9qy2w1tl',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='трассхолдер';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslmgd1grzou5ilsbp54eivhn','трассхолдер','трассхолдер','ceqxrj7uu4gfruzbl9qy2w1tl',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='держатель фермы';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslrhnpxmtxc9adetdeapg11u','держатель фермы','держатель фермы','ceqxrj7uu4gfruzbl9qy2w1tl',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='пленка';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl8mnbsbc1ldpr724mweqehb','пленка','пленка','ceqsebw600s3jd6c4lnlke1gw',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='пленки';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslwctwung5oxn67veqors4dv','пленки','пленки','ceqsebw600s3jd6c4lnlke1gw',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='пленка';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl0f34fcnazf7r6k69j2jyq9','пленка','плёнка','ceqsebw600s3jd6c4lnlke1gw',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='отражатель пена';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl47kh1n99hbi6eicvyt3jlb','отражатель пена','отражатель пена','ceqsebw600s3jd6c4lnlke1gw',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='отражатель пленка';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslw9oc2fyn0fuq0xgd7wuucm','отражатель пленка','отражатель пленка','ceqsebw600s3jd6c4lnlke1gw',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='синее кабло';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csla4ort4yt4nfqjdl9yie3rt','синее кабло','синее кабло','cmn3j5g45006lvastsz54jtg4',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='синий кабель 32';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslmpclx2khf93q0i63ofmgqs','синий кабель 32','синий кабель 32','cmn3j5g45006lvastsz54jtg4',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='32а синее';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslqy27qt6vim4g5ccgynjgxw','32а синее','32а синее','cmn3j5g45006lvastsz54jtg4',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='кабель 32 синий';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl1uwscegv8l702e1bzf61sn','кабель 32 синий','кабель 32 синий','cmn3j5g45006lvastsz54jtg4',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='синее кабель';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csll0lop1srp23c680jhjqjth','синее кабель','синее кабель','cmn3j5g45006lvastsz54jtg4',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='32 синее';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl56c77297pcggcjl8vhebdo','32 синее','32 синее','cmn3j5g45006lvastsz54jtg4',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='блок тайп си двойной';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslc27izfsbzjh5smm69am3vz','блок тайп си двойной','блок тайп си двойной','ceqv51u9dlvwbe893g3kk6a73',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='блок type c двойной';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslajlfyn7589e4mstqvc3e1j','блок type c двойной','блок type c двойной','ceqv51u9dlvwbe893g3kk6a73',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='блок тайп си';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslbtuhi4zw85au8ke1151pfb','блок тайп си','блок тайп си','ceqv51u9dlvwbe893g3kk6a73',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='блок тайпси двойной';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csluywzuvv725n73tkq77s8pv','блок тайпси двойной','блок тайпси двойной','ceqv51u9dlvwbe893g3kk6a73',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='двойной блок тайп си';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslyrqpihji9hxnkyfymq0z9m','двойной блок тайп си','двойной блок тайп си','ceqv51u9dlvwbe893g3kk6a73',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='колья';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl936r17cwi6gedvqd6dmlgk','колья','колья','cequ01gluxbdb1dt0w3tknaon',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='фалы колья';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslkogesgvt0nhrb1wmg9dt4j','фалы колья','фалы колья','cequ01gluxbdb1dt0w3tknaon',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='колышки';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl5k8xvfr3ke2irdxgq6g3sg','колышки','колышки','cequ01gluxbdb1dt0w3tknaon',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='веревки';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl1nwik4unak794gbzo7w3wg','веревки','веревки','cmn3j5g010049vastks2ybu0i',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='веревка';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslxeg57q6iz251y9xrpwmf17','веревка','веревка','cmn3j5g010049vastks2ybu0i',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='веревки';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl3us834qeeldccerj4h9lww','веревки','верёвки','cmn3j5g010049vastks2ybu0i',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='веревка';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csly8z6535rrgtb0mc35vgz1t','веревка','верёвка','cmn3j5g010049vastks2ybu0i',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='веревок';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl5j70fgs4w4bxmak08emf3r','веревок','веревок','cmn3j5g010049vastks2ybu0i',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='систендница';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslq4b08m7bfs1cgnll4pm3sn','систендница','систендница','ceq1fl37t6kvqthuka4ovv4k4',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='систендница фулловая';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslty6d4ldijk5fqgtrfmaetf','систендница фулловая','систендница фулловая','ceq1fl37t6kvqthuka4ovv4k4',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='систстендница';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl4n74dtw5jcjm2sxmuqz97g','систстендница','систстендница','ceq1fl37t6kvqthuka4ovv4k4',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='тележка для систендов';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csltab42xc66is6pd6j3b3b5h','тележка для систендов','тележка для систендов','ceq1fl37t6kvqthuka4ovv4k4',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='телега для стендов';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl1dmn9e4azhtsi42wbaks8d','телега для стендов','телега для стендов','ceq1fl37t6kvqthuka4ovv4k4',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='систендница фуловая';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslohfyke5e5ii7lpw7901kj6','систендница фуловая','систендница фуловая','ceq1fl37t6kvqthuka4ovv4k4',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='лайт дом 120';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl7mpfe18mldfx6p1mnmx1sj','лайт дом 120','лайт дом 120','ceqw0b57m0ddzh9u4yadvgqif',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='лайтдом 120';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csll18lkw21n3mffp7ubt9te7','лайтдом 120','лайтдом 120','ceqw0b57m0ddzh9u4yadvgqif',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='light dome 120';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslpqshb14bgad822bvdz3sxg','light dome 120','light dome 120','ceqw0b57m0ddzh9u4yadvgqif',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='дом 120';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslrf15vvgb5f7dni3ae35unq','дом 120','дом 120','ceqw0b57m0ddzh9u4yadvgqif',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='лайт дом 120 см';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslazdvimqax9qzxrosd555v4','лайт дом 120 см','лайт дом 120 см','ceqw0b57m0ddzh9u4yadvgqif',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;