BEGIN TRANSACTION;
DELETE FROM SlangAlias WHERE phraseNormalized='b150';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl07r050lgg21r2enj1c0s9u','b150','b150','cmn3j5fw1002bvastnymevw6f',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='зарядка для вимаунтов двойная';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslxoocu7q5mlpyiz6syp8b8l','зарядка для вимаунтов двойная','зарядка для вимаунтов двойная','cequap642uuc482a79mx9n2ms',0.9,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='телега с каблом';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslj77lksnqc3f3x85dr7a31l','телега с каблом','телега с каблом','cmn3j5g4f006qvastwiw2bf6k',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='телега с каблом 380';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslgj6cjbt6cncmmyykz3zx5j','телега с каблом 380','телега с каблом 380','cmn3j5g4f006qvastwiw2bf6k',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='телега для кабла';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csluycz6ghau3ikk1imawa80m','телега для кабла','телега для кабла','cmn3j5g4f006qvastwiw2bf6k',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='телега для мешков';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslvd2wxei8c6woooz07ifkbm','телега для мешков','телега для мешков','cmn3j5g4f006qvastwiw2bf6k',0.75,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='3м 42 трубы';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csloao2s5rd493f2m9ks5t9io','3м 42 трубы','3м 42 трубы','cmn3j5g0d004gvastr3nefnlh',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='трубы 3м 42';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csly3bgl6yo59lfu9crlp5t72','трубы 3м 42','трубы 3м 42','cmn3j5g0d004gvastr3nefnlh',0.85,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='3м 42';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('cslgwoos26z7nr02e8p9pdzg1','3м 42','3м 42','cmn3j5g0d004gvastr3nefnlh',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
DELETE FROM SlangAlias WHERE phraseNormalized='трубы 3 42';
INSERT OR IGNORE INTO SlangAlias (id,phraseNormalized,phraseOriginal,equipmentId,confidence,source,usageCount,lastUsedAt,createdAt,updatedAt) VALUES ('csl7judi974nqrixoqg0013le','трубы 3 42','трубы 3 42','cmn3j5g0d004gvastr3nefnlh',0.8,'MANUAL_ADMIN',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;